Feature/HIR-23.  Add endpoints to manage room's allocation requirements according to a season.
happy-travel/hiroshima pull request #27
Opened 2020-08-21 15:48 UTC by oleg1std

Add endpoints to manage the room's allocation requirements according to a season's range.
1. Add allocation requirements
2. Get allocation requirements (all, filter by room, season, date range)
3. Remove allocation requirements.

Remove the DataSeeder project.

2020-08-24 17:43 UTC, oleg1std commented on HappyTravel.Hiroshima.Data/Models/RoomAndAccommodation.cs
> +    public class RoomAndAccommodation
Usually, such classes represent JOIN result. 
E.g.:
 IQueryable<RoomAndAccommodation> GetRoomsAndAccommodations(this DirectContractsDbContext dbContext)
or
IQueryable<SeasonAndSeasonRange> GetSeasonsAndSeasonRanges(this DirectContractsDbContext dbContext)
It's used in several places.
Using tuples entails the error: An expression tree may not contain a tuple literal

2020-08-24 17:50 UTC, oleg1std commented on HappyTravel.Hiroshima.Data/Models/Rooms/RoomAllocationRequirement.cs
> +        public int? MinimumLengthOfStay { get; set; }
I've changed the previous name to MinumulLengthOfStay because I saw the MLOS abbreviature in the Hazel's email 
E.g.:
```
High 1: All have 21 days release and No MLOS – therefore, al dates are under one grid in allocation
08 Jan – 14 Jan (21 days release NO MLOS)
25 Jan – 07 Feb (21 days release NO MLOS)
22 Feb – 20 Mar (21 days release NO MLOS)
19 Apr – 03 May (21 days release NO MLOS)
```

2020-08-24 18:47 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Models/Requests/AllocationRequirement.cs
> +        public int? MinimumLengthOfStay { get; set; }
commonly used abbreviation MLOS

2020-08-24 19:51 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/SeasonManagementService.cs
> +                    .Where(seasonAndSeasonRange => seasonAndSeasonRange.Season.ContractId == contractId && seasonAndSeasonRange.Season.Id == seasonId)
There is a filter below. We have to get contracted season ranges only

2020-08-24 20:00 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/AllocationRequirementManagementService.cs
> +                var seasonsRanges = _dbContext.GetSeasonsAndSeasonRanges()
A season contains information about a contract. We have to get only contracted season ranges.

2020-08-25 08:24 UTC, kirillta commented on HappyTravel.Hiroshima.Data/Models/RoomAndAccommodation.cs
> +    public class RoomAndAccommodation
That's exactly what I mean. A joined entity must represents a reasonable object. If it isn't then better make two requests

2020-08-25 08:40 UTC, kirillta commented on HappyTravel.Hiroshima.Data/Extensions/ContractManagementQueryExtensions.cs
> +            return inappropriateSeasonIds.Any()
The name doesn't fixed

2020-08-25 08:40 UTC, kirillta commented on HappyTravel.Hiroshima.Data/Models/RoomAndAccommodation.cs
> +    public class RoomAndAccommodation
Could you use [that feature](https://docs.microsoft.com/en-us/ef/core/querying/related-data) instead of joins?

2020-08-25 08:42 UTC, kirillta requested changes

2020-08-25 08:42 UTC, kirillta commented on HappyTravel.Hiroshima.DirectManager/Infrastructure/Extensions/ContractManagerExtensions.cs
> +                $"Contract '{contractId}' doesn't belong to the contract manager");
Still not clear what or who is the contract manager

2020-08-25 21:03 UTC, oleg1std commented on HappyTravel.Hiroshima.Data/Models/RoomAndAccommodation.cs
> +    public class RoomAndAccommodation
I've changed this. But this approach implies foreign keys creation.  i.e. ef migrations tool creates foreign keys in this case.

2020-08-26 06:13 UTC, kirillta approved these changes

2020-08-26 07:40 UTC, merged