Feature/hir 91 add endpoint to upload files of contracts
happy-travel/hiroshima pull request #42
Opened 2020-10-07 14:08 UTC by AlexeyShok

2020-10-07 14:37 UTC, AlexeyShok commented
Added POST and DELETE for contract documents and images.

2020-10-07 18:03 UTC, oleg1std commented on HappyTravel.Hiroshima.Common/Infrastructure/VaultHelper.cs
> +                    amazonS3Config.RegionEndpoint = RegionEndpoint.EUWest1;
You can use
 amazonS3Config.RegionEndpoint = RegionEndpoint.GetBySystemName(amazonS3Credentials["regionEndpoint"])

2020-10-07 18:06 UTC, oleg1std commented on HappyTravel.Hiroshima.Data/Migrations/20200927065222_AddTableDocuments.cs
> +                    table.ForeignKey(
We don't use Foreign Keys

2020-10-07 18:09 UTC, oleg1std commented on HappyTravel.Hiroshima.Data/Migrations/20200927065222_AddTableDocuments.cs
> +                    Id = table.Column<int>(nullable: false)
Use UUID as an id for files

2020-10-07 18:12 UTC, oleg1std commented on HappyTravel.Hiroshima.Data/Migrations/20201007134944_AddTableImages.cs
> +                    Id = table.Column<int>(nullable: false)
Better to use a UUID as a primary key

2020-10-07 18:13 UTC, oleg1std commented on HappyTravel.Hiroshima.Data/Migrations/DirectContractsDbContextModelSnapshot.cs
> +                        .HasForeignKey("ContractId")
We don't use foreign keys

2020-10-07 18:27 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/DocumentManagementService.cs
> +            _bucketName = "happy-travel-dc";
Use constants

2020-10-07 18:30 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/DocumentManagementService.cs
> +            return _contractManagerContext.GetContractManager()
You have to check if a contract belongs to a contract manager.

2020-10-07 18:39 UTC, oleg1std commented on nuget.config
> +  <add key="Dotnet5" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json" />
What the reason to use this?

2020-10-07 18:46 UTC, oleg1std commented on HappyTravel.Hiroshima.WebApi/appsettings.json
> +    "S3": {
Better call it "AmazonS3"

2020-10-07 18:50 UTC, oleg1std commented on HappyTravel.Hiroshima.WebApi/Controllers/DirectManager/DocumentManagementController.cs
> +            var document = new Hiroshima.DirectManager.Models.Requests.Document
I don't think it is a good idea to create an additional entity to store an uploaded file and a contract Id.
It's better to pass a contract Id as an argument of the Add method.

2020-10-07 18:52 UTC, oleg1std commented on HappyTravel.Hiroshima.WebApi/Controllers/DirectManager/DocumentManagementController.cs
> +            var document = new Hiroshima.DirectManager.Models.Requests.Document
Moreover, it must be file size limitations.

2020-10-07 18:54 UTC, oleg1std commented on HappyTravel.Hiroshima.WebApi/HappyTravel.Hiroshima.WebApi.xml
> +            Upload file of the contract
Uploads a document to a contract

2020-10-07 18:54 UTC, oleg1std commented on HappyTravel.Hiroshima.WebApi/HappyTravel.Hiroshima.WebApi.xml
> +            Delete file of the contract by ID
Deletes a document from a contract

2020-10-07 18:55 UTC, oleg1std commented on HappyTravel.Hiroshima.WebApi/HappyTravel.Hiroshima.WebApi.xml
> +            Delete file of the contract by ID
check the other comments below

2020-10-07 19:03 UTC, oleg1std commented on HappyTravel.Hiroshima.WebApi/Startup.cs
> +            var amazonS3ClientOptions = VaultHelper.GetAmazonS3Credentials(vaultClient, "DirectContracts:S3:Contracts", Configuration);
AmazonS3ClientOptions are supposed to be used in AmazonS3Client

2020-10-07 19:07 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/DocumentManagementService.cs
> +            return await _contractManagerContext.GetContractManager()
What if contractManager decides to delete a document which belongs to the other manager.

2020-10-07 19:09 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +
Please add an additional line

2020-10-07 19:11 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +
add a line

2020-10-07 19:12 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/DocumentManagementService.cs
> +
add a new line

2020-10-07 19:13 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/DocumentManagementService.cs
> +
add an empty line

2020-10-07 19:17 UTC, oleg1std commented on HappyTravel.Hiroshima.WebApi/Controllers/DirectManager/ImageManagementController.cs
> +            var (_, isFailure, response, error) = await _imageManagementService.Add(image);
Superfluous entity

2020-10-07 19:17 UTC, oleg1std commented on HappyTravel.Hiroshima.WebApi/Controllers/DirectManager/ImageManagementController.cs
> +            var image = new Hiroshima.DirectManager.Models.Requests.Image
Superfluous entity

2020-10-07 19:17 UTC, oleg1std commented on HappyTravel.Hiroshima.WebApi/Controllers/DirectManager/ImageManagementController.cs
> +            var image = new Hiroshima.DirectManager.Models.Requests.Image
in my opinion

2020-10-07 19:19 UTC, oleg1std commented
please check the indents between methods

2020-10-07 19:28 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                dbImage.Key = $"images/{dbImage.AccommodationId}/{dbImage.Name}";
Use a constant for the name of the folder.

2020-10-07 19:31 UTC, oleg1std commented on HappyTravel.Hiroshima.WebApi/Startup.cs
> +            services.AddAmazonS3Client(options =>
Better set options more explicitly.
```
services.AddAmazonS3Client(options =>
            {
                options.AccessKey = "KEY FROM VAULT";
                options.AccessKeyId = "KEY ID FROM VAULT";
                options.AmazonS3Config = new AmazonS3Config
                    {RegionEndpoint = RegionEndpoint.GetBySystemName("NAME FROM VAULT")};
            });
```

2020-10-07 19:39 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectContracts/Services/Management/ContractManagementRepository.cs
> +        public async Task<Document> GetContractDocument(int documentId, int contractId, int contractManagerId) =>
Move it to the service, please.  And check the order of the arguments. GetContractDocument(int contractManagerId, int contractId, int documentId)

2020-10-08 01:41 UTC, AlexeyShok commented on HappyTravel.Hiroshima.WebApi/Controllers/DirectManager/DocumentManagementController.cs
> +            var document = new Hiroshima.DirectManager.Models.Requests.Document
@oleg1std But what about the validator then?

2020-10-08 01:58 UTC, AlexeyShok commented on HappyTravel.Hiroshima.Common/Infrastructure/VaultHelper.cs
> +                    amazonS3Config.RegionEndpoint = RegionEndpoint.EUWest1;
Corrected

2020-10-08 22:49 UTC, kirillta commented on HappyTravel.Hiroshima.WebApi/Startup.cs
> +            string amazonS3Backet = VaultHelper.GetAmazonS3BucketName(vaultClient, "DirectContracts:AmazonS3:Contracts", Configuration);
amazonS3B**u**cket

2020-10-09 13:28 UTC, kirillta requested changes

2020-10-09 13:28 UTC, kirillta commented on HappyTravel.Hiroshima.DirectContracts/Services/Management/ContractManagementRepository.cs
> +using System.Collections.Generic;
The repository adds no extra values and must be removed

2020-10-09 13:28 UTC, kirillta commented on HappyTravel.Hiroshima.Data/Migrations/DirectContractsDbContextModelSnapshot.cs
> +                        .HasColumnType("uuid");
Looks like you have to use `.HasDefaultValueSql("uuid_generate_v4()")` otherwise the default is a constant

2020-10-09 13:28 UTC, kirillta commented on HappyTravel.Hiroshima.Data/Migrations/DirectContractsDbContextModelSnapshot.cs
> +                    b.Property<Guid>("UniqueId")
I think there is a way to name the field as `Id`

2020-10-09 13:32 UTC, kirillta commented on HappyTravel.Hiroshima.DirectManager/Services/DocumentManagementService.cs
> +            return _contractManagerContext.GetContractManager()
On the other hand an administrator may upload contracts too. Anyway let's start from a simple scenario

2020-10-10 12:35 UTC, kirillta approved these changes

2020-10-10 16:21 UTC, oleg1std commented on HappyTravel.Hiroshima.Common/Models/Document.cs
> +        public Guid UniqueId { get; set; }
Id field can be named as "Id"

2020-10-10 16:23 UTC, oleg1std requested changes
Please, rename the Id field as "Id" as it is in other projects

2020-10-10 16:55 UTC, oleg1std commented on HappyTravel.Hiroshima.Common/Models/Contract.cs
> +        [NotMapped]
Do you want to prevent the foreign key creation using this attribute?
You may delete the key in the next migration with an SQL command.
Consequently, the DB snapshot will be with foreign keys, but the DB won't.
It looks like a trick, yet it allows us to preserve relations between models. 
This way request to the DB is simpler.

2020-10-10 16:56 UTC, oleg1std commented on HappyTravel.Hiroshima.Data/DirectContractsDbContext.cs
> +                e.HasKey(c => c.UniqueId);
Please use ID

2020-10-10 17:06 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/RequestValidators/ImageValidator.cs
> +            RuleFor(image => image.AccommodationId).NotEmpty();
It should be image size restrictions

2020-10-10 17:07 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/RequestValidators/DocumentValidator.cs
> +        public DocumentValidator()
Miss document size restrictions

2020-10-10 17:21 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/DocumentManagementService.cs
> +                .Bind(contractManager =>
please, use EnsureContractBelongsToContractManager

2020-10-10 17:22 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/DocumentManagementService.cs
> +                .Map(dbDocument => Build(dbDocument));
You can replace it with method group

2020-10-10 17:24 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/DocumentManagementService.cs
> +                string extension = Path.GetExtension(uploadedFile.FileName);
you can use var

2020-10-10 17:32 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/DocumentManagementService.cs
> +                var result = await _amazonS3ClientService.Add(_bucketName, dbDocument.Key, uploadedFile.OpenReadStream());
What if the result is Failure?

2020-10-10 17:34 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/DocumentManagementService.cs
> +                var result = await _amazonS3ClientService.Add(_bucketName, dbDocument.Key, uploadedFile.OpenReadStream());
It's not 200 for sure

2020-10-10 17:38 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/DocumentManagementService.cs
> +                var result = await _amazonS3ClientService.Delete(_bucketName, document.Key);
It can be Failure here

2020-10-10 17:39 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                var result = await _amazonS3ClientService.Add(_bucketName, dbImage.Key, uploadedFile.OpenReadStream());
It can be Failure

2020-10-10 17:47 UTC, oleg1std commented on HappyTravel.Hiroshima.WebApi/Controllers/DirectManager/DocumentManagementController.cs
> +            var document = new Hiroshima.DirectManager.Models.Requests.Document
I don't see a file size validation here

2020-10-10 17:48 UTC, oleg1std commented on HappyTravel.Hiroshima.WebApi/Controllers/DirectManager/DocumentManagementController.cs
> +            var document = new Hiroshima.DirectManager.Models.Requests.Document
It's in the controller

2020-10-10 17:57 UTC, oleg1std commented
We discussed that the image endpoints would return two s3 URI in the response.  For details, please ask @alexander-plekhanov

2020-10-11 10:29 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/DocumentManagementService.cs
> +                .Ensure(dbDocument => dbDocument != null, $"Error saving document to Amazon S3")
No need to expose to the client our file storage

2020-10-11 10:30 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/DocumentManagementService.cs
> +                else
if (result.IsFailure)
 return null;

2020-10-11 15:20 UTC, oleg1std approved these changes

2020-10-11 15:26 UTC, merged