Feature/hir 96 add endpoint to upload accommodation photos
happy-travel/hiroshima pull request #46
Opened 2020-10-19 17:37 UTC by AlexeyShok

Added validation and resizing images. Two images now saved to Amazon S3 in POST. Too, two images deleted in DELETE. Changes endpoints for images according to task. Renamed prorperties in Image model for correct. Added receiving List<Images> to GET for accommodation.

2020-10-19 20:22 UTC, kirillta requested changes

2020-10-19 20:22 UTC, kirillta commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
>                      return null;
Please avoid using nulls. 
See [Maybe](https://github.com/vkhorikov/CSharpFunctionalExtensions#make-nulls-explicit-with-the-maybe-type)

2020-10-19 20:22 UTC, kirillta commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +        private const int maximumSideSizeLarge = 1600;
My amateur camera have 4272x2848 resolution. This limitations too severe

2020-10-19 20:22 UTC, kirillta commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                    return Result.Failure<byte[]>("Uploading picture dimension difference is more then the maximum");
Please, add more details to the error message, like you check against 2 but writes about a "maximum"

2020-10-19 20:22 UTC, kirillta commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +            async Task<Result<byte[]>> ValidateImage(FormFile uploadedFile)
This method validates and returns an array in the same time. A method must have only one job

2020-10-19 20:22 UTC, kirillta commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                using (var imageJob = new ImageJob())
Use the new using syntax

2020-10-19 20:22 UTC, kirillta commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                        .EncodeToBytes(new MozJpegEncoder(targetJpegQuality, true))
Why this line doubles?

2020-10-19 20:22 UTC, kirillta commented on HappyTravel.Hiroshima.DirectContracts/Services/Management/ContractManagementRepository.cs
> +        public async Task<Contract> GetContract(int contractId, int contractManagerId)
Please, move this repository to a service

2020-10-19 20:38 UTC, AlexeyShok commented on HappyTravel.Hiroshima.DirectManager/Services/DocumentManagementService.cs
> +                entry.Entity.Key = $"{S3FolderName}/{dbDocument.ContractId}/{entry.Entity.Id}{extension}";
Yes, it's more convenient to work with files this way.

2020-10-19 20:56 UTC, AlexeyShok commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                        .EncodeToBytes(new MozJpegEncoder(targetJpegQuality, true))
First .EncodeToBytes(new MozJpegEncoder(targetJpegQuality, true)) for branch, second for main image job

2020-10-20 16:51 UTC, AlexeyShok commented on HappyTravel.Hiroshima.DirectContracts/Services/Management/ContractManagementRepository.cs
> +        public async Task<Contract> GetContract(int contractId, int contractManagerId)
I moved the method from the repository to the service. But I have not yet transferred other methods from there. We need to think about refactoring first. If we just transfer the methods, we get a very confusing service.

2020-10-20 20:48 UTC, kirillta commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +            async Task<Result<Image>> AddImage(Image dbImage, FormFile uploadedFile)
Must be `Maybe<Image>` or `Image?`

2020-10-20 20:48 UTC, kirillta commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                var stream = new MemoryStream(imageSet.LargeImage);
Still not fixed

2020-10-20 20:48 UTC, kirillta commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +        private const int maximumSideSizeLarge = 1600;
Up

2020-10-20 20:55 UTC, kirillta requested changes

2020-10-20 20:55 UTC, kirillta commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                .Tap(dbImage => AddImage(dbImage, image.UploadedFile))
I doubt it should be tap at this line

2020-10-20 20:55 UTC, kirillta commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                using (BinaryReader binaryReader = new BinaryReader(uploadedFile.OpenReadStream()))
Use the new syntax either remove braces

2020-10-21 04:37 UTC, AlexeyShok commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +        private const int maximumSideSizeLarge = 1600;
These restrictions are set in the task. If the image has more than 1600 pixels on either side, it is scaled to 1600 pixels.

2020-10-21 11:49 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                var extension = Path.GetExtension(uploadedFile.FileName).ToLower();
Possible null reference exception. Conditional access can be used.

2020-10-21 12:26 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                    return Result.Failure<byte[]>("Uploading picture size is less than the minimum");
It's not clear what is the minimum size of the image

2020-10-21 12:49 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Models/Responses/Contract.cs
> +
Extra line

2020-10-21 12:51 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
>                      return validationResult.IsFailure ? Result.Failure<ContractManager>(validationResult.Error) : Result.Success(contractManager);
You can use
 .Tap(contractManager => ValidationHelper.Validate(image, new ImageValidator()))

2020-10-21 12:55 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                .Map(maybeImage => Build(maybeImage));
You can replace it with method group

2020-10-21 12:57 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                ImageSet imagesSet = new ImageSet();
var can be used

2020-10-21 12:59 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                imagesSet.SmallImage = jobResult.TryGet(1).TryGetBytes().Value.ToArray();
possible InvalidOperationException
use conditional access

2020-10-21 13:02 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                    return Result.Failure<byte[]>("Uploading picture width is more than 2 times the height");
The method returns Task<Result>

2020-10-21 13:06 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                using var smallStream = new MemoryStream(imageSet.SmallImage);
await using can be used
IAsyncDisposable

2020-10-21 13:08 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                using var largeStream = new MemoryStream(imageSet.LargeImage);
"await using" can be used here

2020-10-21 13:13 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                byte[] imageBytes = null;
Redundant initializer. Besides, you can join declaration and assignment

2020-10-21 13:49 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                    return Result.Failure<byte[]>("Uploading picture size is less than the minimum");
you can use something like this "Image must be at least 640×480 pixels and at most 1920×1080"

2020-10-21 13:52 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
>                  var extension = Path.GetExtension(uploadedFile.FileName);
Unused variable

2020-10-21 13:57 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +            async Task<Result<Maybe<Image>>> AppendContent(Image dbImage, FormFile uploadedFile)
The method is too long. Could you split it?

2020-10-21 13:58 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +            async Task<Result<Maybe<Image>>> AppendContent(Image dbImage, FormFile uploadedFile)
Or structurize it with sub-methods

2020-10-21 14:07 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/AccommodationManagementService.cs
> +                    ? accommodation.Images.Select(image => new Models.Responses.Image
It's hard to read. Please, use local variable

2020-10-21 14:08 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ContractManagementService.cs
> +                    ? contract.Documents.Select(document => new Models.Responses.Document
It's hard to read

2020-10-21 14:45 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/DocumentManagementService.cs
> +
Pay attention to the highlighted LINQ expression below.
```var document = await _dbContext.Documents.SingleOrDefaultAsync(c => c.ContractManagerId == contractManagerId && c.ContractId == contractId && c.Id == documentId);```
Why the argument has been called "c"?

2020-10-21 14:47 UTC, oleg1std commented
Please arrange the sub-methods in the methods according to their order usage.

2020-10-21 15:03 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/DocumentManagementService.cs
> +
"var" can be used in the result below instead of bool

2020-10-21 16:11 UTC, kirillta commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +        private const int MaximumSideSizeLarge = 1600;
Still can't understand what means "maximum" in the context? Are images can't be larger than this value?

2020-10-21 16:11 UTC, kirillta commented on HappyTravel.Hiroshima.DirectManager/Services/AccommodationManagementService.cs
> +                accommodation.Images != null
To avoid this check, create accommodations with an empty list of images

2020-10-21 16:11 UTC, kirillta commented on HappyTravel.Hiroshima.Common/Models/Image.cs
>      public class Image
Why this class calls `Image` if it contains only metadata, though?

2020-10-21 23:49 UTC, AlexeyShok commented on HappyTravel.Hiroshima.Common/Models/Image.cs
>      public class Image
We use the same names for the general model, request and response. But in the request Image contains the image file. Therefore, the class is called Image everywhere.

2020-10-22 08:38 UTC, kirillta approved these changes
Approved with @oleg1std comments in mind

2020-10-22 20:33 UTC, oleg1std requested changes
The methods RemoveImageFile and AddImageFile shouldn't allow anonymous access

2020-10-23 09:14 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/HappyTravel.Hiroshima.DirectManager.csproj
> +      <PackageReference Include="Imageflow.Net" Version="0.7.7" />
Two same package reference here

2020-10-23 09:36 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ContractManagerContextService.cs
> +            var contractManager = await _dbContext.ContractManagers.SingleOrDefaultAsync(manager => manager.Id == 5);
omg. please fix this

2020-10-23 09:36 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ContractManagerContextService.cs
> +        //    => await _dbContext.ContractManagers.SingleOrDefaultAsync(contractManager => contractManager.IdentityHash == GetIdentityHash()) != null;
and this

2020-10-23 09:56 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                /*                await using var largeStream = new MemoryStream(imageSet.LargeImage);
Remove this

2020-10-23 10:02 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                        _dbContext.Images.Remove(entry.Entity);
What if the first upload is successful but the next one isn't?

2020-10-23 10:09 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                var extension = uploadedFile != null ? Path.GetExtension(uploadedFile.FileName).ToLower() : string.Empty;
You can use conditional access here

2020-10-23 10:11 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                /*                await using var largeStream = new MemoryStream(imageSet.LargeImage);
commentary

2020-10-23 10:14 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                imagesSet.SmallImage = (jobResult != null && jobResult.TryGet(1) != null && jobResult.TryGet(1).TryGetBytes() != null)
Sequential checks can be merged

2020-10-23 10:16 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                imagesSet.SmallImage = (jobResult != null && jobResult.TryGet(1) != null && jobResult.TryGet(1).TryGetBytes() != null)
Possible InvalidOperationException

2020-10-23 10:17 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                    ? jobResult.TryGet(1).TryGetBytes().Value.ToArray()
Possible InvalidOperationException

2020-10-23 10:17 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                    ?jobResult.TryGet(2).TryGetBytes().Value.ToArray()
Possible InvalidOperationException

2020-10-23 10:29 UTC, oleg1std commented on HappyTravel.Hiroshima.WebApi/HappyTravel.Hiroshima.WebApi.csproj
> +    <PackageReference Include="Imageflow.NativeRuntime.ubuntu_16_04-x86_64" Version="1.4.11-rc51" />
There is a code duplication here

2020-10-23 10:35 UTC, oleg1std commented on HappyTravel.Hiroshima.WebApi/Controllers/DirectManager/AccommodationManagementController.cs
> +        [AllowAnonymous]
Please, remove this

2020-10-26 08:50 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                    for (int i = 0; i < images.Count; i++)
You can use var here

2020-10-26 09:12 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +            var image = await _dbContext.Images.SingleOrDefaultAsync(c => c.ContractManagerId == contractManagerId && c.AccommodationId == accommodationId && c.Id == imageId);
irrelevant argument name

2020-10-26 09:14 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +            foreach (Image image in images)
"var" could be used here

2020-10-26 09:23 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/DocumentManagementService.cs
> +                using BinaryReader binaryReader = new BinaryReader(stream.Value);
var could be used here

2020-10-26 10:04 UTC, oleg1std approved these changes

2020-10-26 10:08 UTC, merged