HIR-26. The first step of the availability search
happy-travel/hiroshima pull request #52
Opened 2020-10-30 19:28 UTC by oleg1std

The first step of the availability search

2020-10-30 20:52 UTC, kirillta requested changes

2020-10-30 20:52 UTC, kirillta commented on HappyTravel.Hiroshima.WebApi/Controllers/Connector/AccommodationsController.cs
> +        [AllowAnonymous]
Why?

2020-10-30 20:52 UTC, kirillta commented on HappyTravel.Hiroshima.WebApi/Infrastructure/Extensions/ServiceCollectionExtensions.cs
> +            services.AddSingleton<IRateResponseService, RateResponseService>();
Why singletons?

2020-10-30 20:52 UTC, kirillta commented on HappyTravel.Hiroshima.WebApi/Services/AccommodationResponseService.cs
> +        public SlimAccommodation Create(Accommodation accommodation, string languageCode)
This looks like a static class

2020-10-30 20:52 UTC, kirillta commented on HappyTravel.Hiroshima.Common/Constants/Languages.cs
> +        private const string ArabicLanguageCode = "AR";
We use lower cased language codes across the system

2020-10-30 20:53 UTC, kirillta commented on HappyTravel.Hiroshima.Common/Constants/Languages.cs
> +        private const string ArabicLanguageCode = "AR";
Also we decided to use `MoneyAmount` everywhere possible

2020-10-31 12:31 UTC, oleg1std commented on HappyTravel.Hiroshima.WebApi/Infrastructure/Extensions/ServiceCollectionExtensions.cs
> +            services.AddSingleton<IRateResponseService, RateResponseService>();
There are no shared resources for now

2020-10-31 12:35 UTC, oleg1std commented on HappyTravel.Hiroshima.WebApi/Services/AccommodationResponseService.cs
> +        public SlimAccommodation Create(Accommodation accommodation, string languageCode)
The Singleton pattern has several advantages over static classes

2020-10-31 12:40 UTC, oleg1std commented on HappyTravel.Hiroshima.Common/Constants/Languages.cs
> +        private const string ArabicLanguageCode = "AR";
It has a private modifier. It is used for getting language value by language code.

2020-10-31 12:42 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectContracts/Models/PaymentDetails.cs
> +        public decimal PriceTotal { get; }
It's not about English, it's about c# conventions. I'll fix it.

2020-11-01 18:44 UTC, kirillta commented on HappyTravel.Hiroshima.Common/Models/Accommodations/Accommodation.cs
> +        public override bool Equals(object? obj)
We have a conventional implementation for `Equals`. Please use it

2020-11-01 18:44 UTC, kirillta commented on HappyTravel.Hiroshima.DirectManager/Models/Responses/DocumentFile.cs
>      public readonly struct DocumentFile
Why not `Document`?

2020-11-01 18:44 UTC, kirillta commented on HappyTravel.Hiroshima.DirectManager/Models/Responses/PromotionalOfferStopSale.cs
> +
Promotional offer stop sale what? The name is inconsistent

2020-11-01 18:44 UTC, kirillta commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +            SmallImageUri = string.Empty,
These four properties may be refactored as a nested entity, like `Small.Url` etc

2020-11-01 18:44 UTC, kirillta commented on HappyTravel.Hiroshima.WebApi/Infrastructure/Extensions/ServiceCollectionExtensions.cs
> +            services.AddSingleton<IRateResponseService, RateResponseService>();
This assertion is dangerous

2020-11-01 18:45 UTC, kirillta reviewed
Also we decided to use `MoneyAmount` everywhere possible

2020-11-01 19:08 UTC, kirillta requested changes

2020-11-01 19:08 UTC, kirillta commented on HappyTravel.Hiroshima.WebApi/Services/RateResponseService.cs
> +    public class RateResponseService : IRateResponseService
Why `RateResponseService` calculates deadlines and contract sets? Also why it calls _Rate_ service? We need a decision about terminology

2020-11-01 19:08 UTC, kirillta commented on HappyTravel.Hiroshima.Common/Models/Image.cs
> +        public string LargeImageUri { get; set; }
If we have a small and a large images, which one should I use? Shouldn't this one be a normal or a usual?

2020-11-02 08:49 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Models/Responses/DocumentFile.cs
>      public readonly struct DocumentFile
@AlexeyShok

2020-11-02 09:14 UTC, AlexeyShok commented on HappyTravel.Hiroshima.DirectManager/Models/Responses/DocumentFile.cs
>      public readonly struct DocumentFile
We have two different responses. One returns model data, the other returns document file. Therefore, it is logical to name one Document, and the second DocumenFile.

2020-11-02 09:15 UTC, oleg1std commented on HappyTravel.Hiroshima.WebApi/Services/RateResponseService.cs
> +    public class RateResponseService : IRateResponseService
The Rate response service creates a response according to the interservice contracts. I'll rename CalculateSmb methods to Create

2020-11-02 09:18 UTC, AlexeyShok commented on HappyTravel.Hiroshima.Common/Models/Image.cs
> +        public string LargeImageUri { get; set; }
Both options are used. Small ones are shown as a collection, when clicked to view, a large image is loaded.

2020-11-02 09:25 UTC, oleg1std commented on HappyTravel.Hiroshima.Common/Models/Image.cs
> +        public string LargeImageUri { get; set; }
I'll rename this to Image. But I have to admit this task is not about images.

2020-11-02 10:50 UTC, oleg1std commented on HappyTravel.Hiroshima.Common/Models/Image.cs
> +        public string LargeImageUri { get; set; }
It will be fixed in HIR-111

2020-11-02 10:50 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +            SmallImageUri = string.Empty,
Will be fixed in HIR-111

2020-11-02 12:23 UTC, kirillta commented on HappyTravel.Hiroshima.DirectManager/Models/Responses/DocumentFile.cs
>      public readonly struct DocumentFile
OK, understood

2020-11-03 10:14 UTC, kirillta requested changes

2020-11-03 10:14 UTC, kirillta commented on HappyTravel.Hiroshima.WebApi/Services/AvailabilityResponseService.cs
> +        private List<SlimAccommodationAvailability> CreateSlimAccommodationAvailabilities(Dictionary<Accommodation, List<AvailableRates>> accommodationAvailableRatesStore, string languageCode)
A private method must be placed after public ones

2020-11-03 10:14 UTC, kirillta commented on HappyTravel.Hiroshima.WebApi/Services/AvailabilityResponseService.cs
> +        public Availability Create(AvailabilityRequest availabilityRequest, Dictionary<Accommodation, List<AvailableRates>> accommodationAvailableRatesStore, string languageCode)
Two completely different `Create` methods in one class

2020-11-03 11:07 UTC, kirillta approved these changes

2020-11-03 11:08 UTC, merged