Modify the image model in the DB and AddImage endpoint refactoring
happy-travel/hiroshima pull request #54
Opened 2020-11-04 14:36 UTC by oleg1std

Modify the image model in the DB and modify the "AddImage" endpoint

2020-11-04 15:35 UTC, AlexeyShok requested changes

2020-11-04 15:35 UTC, AlexeyShok commented on HappyTravel.Hiroshima.WebApi/Controllers/DirectManager/ImageManagementController.cs
> +        [ProducesResponseType(typeof(int), (int)HttpStatusCode.OK)]
Image id is Guid, not int

2020-11-04 15:35 UTC, AlexeyShok commented on HappyTravel.Hiroshima.WebApi/Services/AccommodationResponseService.cs
>             firstImage.Description.GetValue<MultiLanguage<string>>().TryGetValueOrDefault(languageCode,out var caption);
Please, add space before "out"

2020-11-04 15:35 UTC, AlexeyShok commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +            _basePathToAmazon = $"https://{_bucketName}.s3-{options.Value.AmazonS3RegionEndpoint}.amazonaws.com";
Is the string too difficult to read?

2020-11-04 15:35 UTC, AlexeyShok commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                        dbImage.SmallImage.Url = $"{_basePathToAmazon}/{dbImage.SmallImage.Key}";
I'm not sure if we should save image URL in the database. If we transfer pictures to another S3 bucket or Amazon changes the base URL of buckets, all URLs will be incorrect and a script will need to be written to correct all the records of images in the database.

2020-11-04 17:04 UTC, kirillta requested changes

2020-11-04 17:04 UTC, kirillta commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                    .Tap(ValidateDimension)
Doubtful usage of `Tap`

2020-11-05 11:20 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                    .Tap(ValidateDimension)
"Tap" is used according to the documentation and works just fine:
```If the calling result is a success, the given function is executed and its Result is checked. If this Result is a failure, it is returned. Otherwise, the calling result is returned.``` 
The tap function will take an input, pass it to another function, then return the input unchanged

2020-11-05 11:21 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ImageManagementService.cs
> +                        dbImage.SmallImage.Url = $"{_basePathToAmazon}/{dbImage.SmallImage.Key}";
Has been discussed at the meeting

2020-11-05 13:41 UTC, AlexeyShok approved these changes

2020-11-05 16:32 UTC, kirillta approved these changes

2020-11-05 16:32 UTC, merged