Feature/hir 127 make company registration
happy-travel/hiroshima pull request #73
Opened 2020-12-07 19:08 UTC by AlexeyShok

Added registration for service supplier. Removed FK from Managers table. Some refactoring

2020-12-08 06:50 UTC, mingazhev requested changes

2020-12-08 06:50 UTC, mingazhev commented on HappyTravel.Hiroshima.DirectManager/Services/ManagerManagementService.cs
> +                return await Result.Success()
Why not starting from CreateServiceSupplier?

2020-12-08 06:50 UTC, mingazhev commented on HappyTravel.Hiroshima.DirectManager/Services/ManagerManagementService.cs
> +                .Map(Build);
What is "Built"? Maybe BuildResponse? Or something like ToResponse?

2020-12-08 06:50 UTC, mingazhev commented on HappyTravel.Hiroshima.DirectManager/Services/ManagerManagementService.cs
> +                .Ensure(IdentityHashNotEmpty, "Failed to get the sub claim")
IsIdentityHashNotEmpty

2020-12-08 06:50 UTC, mingazhev commented on HappyTravel.Hiroshima.DirectManager/Services/ManagerManagementService.cs
> +                .Bind(() => IsRequestValid(managerRequest))
Why validating so soon? Shouldn't the request be validated at the start?

2020-12-08 06:50 UTC, mingazhev commented on HappyTravel.Hiroshima.DirectManager/Services/ManagerManagementService.cs
> +           return Result.Success()
Please, avoid starting chains from Result.Success where possible

2020-12-08 06:50 UTC, mingazhev commented on HappyTravel.Hiroshima.DirectManager/Services/ManagerManagementService.cs
> +                .Map(Create)
Could not get what's the difference between create and add from this high-level point of view

2020-12-08 06:50 UTC, mingazhev commented on HappyTravel.Hiroshima.DirectManager/Services/ManagerManagementService.cs
> +                var utcNowDate = DateTime.UtcNow;
Please consider injecting volatile things such as datetime as dependency (IDateTimeProvider)

2020-12-08 06:50 UTC, mingazhev commented on HappyTravel.Hiroshima.WebApi/Controllers/DirectManager/ManagerController.cs
> +    [Route("api/{v:apiVersion}/management/manager")]
Should it be "manager", not "managers" in plural?

2020-12-08 06:50 UTC, mingazhev commented on HappyTravel.Hiroshima.DirectManager/Services/ManagerManagementService.cs
> +                    var relation = new Common.Models.ManagerServiceSupplierRelation
Should relation be in this namespace?
Why not in Data?

2020-12-08 06:50 UTC, mingazhev commented on HappyTravel.Hiroshima.DirectManager/Services/ManagerManagementService.cs
> +        private Result IsRequestValid(Models.Requests.Manager managerRequest)
Method name sound like it returns bool. Maybe ValidateRequest will be better

2020-12-08 06:50 UTC, mingazhev commented on HappyTravel.Hiroshima.DirectManager/Services/ManagerContextService.cs
> +            => await _dbContext.Managers.SingleOrDefaultAsync(manager => manager.IdentityHash == GetIdentityHash()) != null;
Should be there a check that manager is Active?

2020-12-08 06:50 UTC, mingazhev commented on HappyTravel.Hiroshima.DirectManager/Services/ManagerContextService.cs
> +            if (manager.Result.IsFailure)
Blocking thread instead of awaiting. Is it by design?

2020-12-08 06:50 UTC, mingazhev commented on HappyTravel.Hiroshima.DirectManager/Services/ManagerContextService.cs
> +                : Result.Success(serviceSupplier);
You can return just serviceSupplier instead of wrapping to Result.Success

2020-12-08 06:50 UTC, mingazhev commented on HappyTravel.Hiroshima.DirectManager/Services/ManagerManagementService.cs
> +                .Map(ModifyManager)
"ModifyManager" and just "Update".
For similarity both methods should have same method pattern.
And again, I do not see any difference on the high level between Modify and Update.
Looks unuseful info for me

2020-12-08 06:50 UTC, mingazhev commented on HappyTravel.Hiroshima.WebApi/Controllers/DirectManager/ManagerController.cs
> +        public async Task<IActionResult> AddManager([FromBody] Hiroshima.DirectManager.Models.Requests.Manager manager)
Is it adding or registering?
Semantically different cases

2020-12-08 06:50 UTC, mingazhev commented on HappyTravel.Hiroshima.WebApi/Controllers/DirectManager/ManagerController.cs
> +        public async Task<IActionResult> AddCompany([FromBody] Hiroshima.DirectManager.Models.Requests.ServiceSupplier serviceSupplier)
RegisterCompany maybe? And why company?

2020-12-08 06:50 UTC, mingazhev commented on HappyTravel.Hiroshima.DirectManager/Services/ServiceSupplierContextService.cs
> +            return _dbContext.DoesContractBelongToServiceSupplier(contractId, serviceSupplier.Id).Result
Why using blocking thread methods?

2020-12-08 06:50 UTC, mingazhev commented on HappyTravel.Hiroshima.DirectManager/Services/ServiceSupplierContextService.cs
> +            var ifRoomInAccommodationExist = await _dbContext.Rooms.AnyAsync(r => r.Id == roomId && r.AccommodationId == accommodationId);
if?

2020-12-08 06:50 UTC, mingazhev commented on HappyTravel.Hiroshima.DirectManager/Services/ManagerManagementService.cs
> +                1,
Please add a comment for hardcoded value.
It is not obvious what does it mean

2020-12-08 06:50 UTC, mingazhev commented on HappyTravel.Hiroshima.DirectManager/Services/ManagerManagementService.cs
> +                        Modified = utcNowDate
Is this by design? Should not fields be filled?

2020-12-08 13:16 UTC, AlexeyShok commented on HappyTravel.Hiroshima.DirectManager/Services/ManagerManagementService.cs
> +                .Map(Build);
In all services, the construction of a response to a request is named "Build". This is the de facto standard in hiroshima

2020-12-08 13:52 UTC, AlexeyShok commented on HappyTravel.Hiroshima.DirectManager/Services/ManagerManagementService.cs
> +                        Modified = utcNowDate
Yes. In next task will be changed.

2020-12-08 13:55 UTC, AlexeyShok commented on HappyTravel.Hiroshima.WebApi/Controllers/DirectManager/ManagerController.cs
> +        public async Task<IActionResult> AddCompany([FromBody] Hiroshima.DirectManager.Models.Requests.ServiceSupplier serviceSupplier)
Changed to AddServiceSupplier. Will be changed in next subtask

2020-12-08 14:21 UTC, AlexeyShok commented on HappyTravel.Hiroshima.DirectManager/Services/ManagerManagementService.cs
> +                return await Result.Success()
Method will be full chainged in next subtask.

2020-12-08 22:24 UTC, kirillta requested changes

2020-12-08 22:24 UTC, kirillta commented on HappyTravel.Hiroshima.DirectManager/Models/Requests/ServiceSupplier.cs
> +        [Required]
Postal code can't be required

2020-12-08 22:24 UTC, kirillta commented on HappyTravel.Hiroshima.DirectManager/RequestValidators/ServiceSupplierValidator.cs
> +            RuleFor(company => company.PostalCode).NotEmpty();
Same here

2020-12-08 22:24 UTC, kirillta commented on HappyTravel.Hiroshima.DirectManager/Services/ServiceSupplierContextService.cs
> +        public ServiceSupplierContextService(DirectContractsDbContext dbContext)
So basically we have this class only for validation. @mingazhev @oleg1std is that OK for you?

2020-12-09 05:38 UTC, mingazhev reviewed
Some of my comments have neither fixes neither answers. Please, answer to each or make appropriate changes

2020-12-14 19:24 UTC, AlexeyShok commented on HappyTravel.Hiroshima.DirectManager/Services/ManagerManagementService.cs
> +                .Map(Create)
Create means creating an entity, and Add means adding it to the database

2020-12-14 19:28 UTC, AlexeyShok commented on HappyTravel.Hiroshima.DirectManager/Services/ManagerManagementService.cs
> +                    var relation = new Common.Models.ManagerServiceSupplierRelation
In this case, relation is a separate entity, which, in addition to links to bound elements, contains other properties (ManagerPermissions, IsMaster, IsActive)

2020-12-14 19:48 UTC, AlexeyShok commented on HappyTravel.Hiroshima.DirectManager/Services/ManagerManagementService.cs
> +                .Bind(() => IsRequestValid(managerRequest))
In the event of a request validation error, a message will be displayed about which fields are filled incorrectly. I think that first we need to check if the manager has the appropriate permissions. If not, then you do not need to give him detailed information.

2020-12-14 20:21 UTC, AlexeyShok commented on HappyTravel.Hiroshima.DirectManager/Services/ManagerManagementService.cs
> +                var utcNowDate = DateTime.UtcNow;
I agree, IDateTimeProvider is the best solution. But in hirosima it was not used. We can create a separate refactoring task, as we need to fix this in many methods.

2020-12-14 20:31 UTC, AlexeyShok commented on HappyTravel.Hiroshima.DirectManager/Services/ManagerContextService.cs
> +            => await _dbContext.Managers.SingleOrDefaultAsync(manager => manager.IdentityHash == GetIdentityHash()) != null;
No. This is a check if the manager exists. Regardless of IsActive setting

2020-12-14 20:39 UTC, AlexeyShok commented on HappyTravel.Hiroshima.DirectManager/Services/ManagerContextService.cs
> +                : Result.Success(serviceSupplier);
In my opinion, the code reads better this way. We can discuss it at the meeting.

2020-12-14 20:48 UTC, AlexeyShok commented on HappyTravel.Hiroshima.WebApi/Controllers/DirectManager/ManagerController.cs
> +        public async Task<IActionResult> AddManager([FromBody] Hiroshima.DirectManager.Models.Requests.Manager manager)
The code of this request is completely rewritten in the next subtask. It should of course be Register.

2020-12-14 21:38 UTC, AlexeyShok commented on HappyTravel.Hiroshima.DirectManager/Services/ManagerManagementService.cs
> +                .Map(ModifyManager)
In some refactoring book, I came across a recommendation to use different names for the same actions in different layers. Like for example: modify - update, delete - remove. Since we have abandoned the use of repositories, in fact the layer of interaction with the database is in services. Therefore, I consider it correct to named methods working with a database differently than other similar methods. (In this example, in the process of refactoring in the next task, these two methods were combined into one Update.)

2020-12-14 21:41 UTC, AlexeyShok commented on HappyTravel.Hiroshima.WebApi/Controllers/DirectManager/ManagerController.cs
> +    [Route("api/{v:apiVersion}/management/manager")]
We can discuss this in a meeting. It is probably more correct to use a single number, since all requests of this controller work with one manager, unlike other controllers.

2020-12-15 10:58 UTC, AlexeyShok commented on HappyTravel.Hiroshima.DirectManager/Services/ServiceSupplierContextService.cs
> +        public ServiceSupplierContextService(DirectContractsDbContext dbContext)
These methods were moved to a separate service from the extensions, since the transfer of dbContext was required.

2020-12-15 11:02 UTC, oleg1std commented on HappyTravel.Hiroshima.DirectManager/Services/ServiceSupplierContextService.cs
> +        public ServiceSupplierContextService(DirectContractsDbContext dbContext)
I think it is  ok in the current itteration

2020-12-15 11:02 UTC, oleg1std approved these changes

2020-12-15 11:03 UTC, kirillta approved these changes

2020-12-15 11:08 UTC, mingazhev approved these changes

2020-12-15 11:28 UTC, merged